config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :movies, concerns: :paginatable do
    resources :reviews, :concerns => :paginatable
  end

  namespace :admin do
    resources :users, concerns: :paginatable
  end

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  # post 'signup', to: 'users#create', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # post 'login', to: 'sessions#create', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'movies#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_create :confirmation_token

  has_many :reviews

  paginates_per 10

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def self.authenticate_with_salt(user_id,user_salt)
    User.where(id:user_id, salt:user_salt).first
  end

  def full_name
    "#{firstname} #{lastname}"
  end

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(validate: false)
  end

  private

  def confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access
  before_filter :restrict_admin

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

   def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # binding.pry
    @user = User.new(user_params)

    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      flash[:success] = "Please confirm your email address to continue"
      redirect_to root_url
    else
      flash[:error] = "Ooooppss, something went wrong!"
      render 'new'
    end
  end

  def confirm_email
    # binding.pry
    user = User.find_by_confirm_token(params[:id])
    if user
      user.email_activate
      sign_in user
      flash[:success] = "Welcome to the Bad Apples! Your email has been confirmed. Please sign in to continue."
      redirect_to new_session_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>

  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being submitted:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label "email" %><br>
        <%= f.text_field "email", class: "form-control", placeholder: "Enter user email" %>
      </div>
      <div class="form-group">
        <%= f.label "firstname" %><br>
        <%= f.text_field "firstname", class: "form-control", placeholder: "Enter user first name" %>
      </div>
      <div class="form-group">
        <%= f.label "lastname" %><br>
        <%= f.text_field "lastname", class: "form-control", placeholder: "Enter user last name" %>
      </div>
      <div class="form-group">
        <%= f.label "password" %><br>
        <%= f.password_field "password", class: "form-control", placeholder: "Enter user password" %>
      </div>
      <div class="form-group">
        <%= f.label "password_confirmation" %><br>
        <%= f.password_field "password_confirmation", class: "form-control", placeholder: "Enter user password confirmation" %>
      </div>
      <div class="form-group">
        <%= f.label "admin" %><br>
        <%= f.check_box "admin", class: "checkbox", placeholder: "Specify if this user has administrator status" %>
      </div>
      <div class="actions">
        <%= f.submit class: "btn btn-default" %>
      </div>
    <div>
  <div>
<% end %>

app/views/admin/users/edit.html.erb
<%= link_to "Back to this user", admin_user_path([:admin, @user]) %>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>Admin Panel</h1>
<%= link_to "Create a new user", new_admin_user_path %>
<hr>
<% @users.each do |user| %>
  <h2><%= link_to user.full_name, admin_user_path(user) %></h2>
  <h3>Average movie rating 
  <%= user.reviews.average(:rating_out_of_ten).try(:round) %>/10</h3>
  <hr>
<% end %>
<%= paginate @users %>
<%= #TODO offload logic to model/helper %>

app/views/admin/users/new.html.erb
<%= link_to "Back to this user", admin_user_path([:admin, @user]) %>

<%= render 'form' %>

app/views/admin/users/show.html.erb
<%= link_to "Back to all users", admin_users_path %><br/>

<h2><%= @user.full_name %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>)</h2>
<h3><%= mail_to @user.email, @user.email %></h3>
<h4>Average movie rating <%= @user.reviews.average(:rating_out_of_ten) %>/10<h4>

<hr>

<h3>Reviews by <em><%= @user.full_name %></em></h3>
  <% @user.reviews.each do |review| %>
    <p><%= review.text %></p>
    <p><%= review.rating_out_of_ten %>/10</p>
  <% end %>