config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :movies, concerns: :paginatable do
    resources :reviews, :concerns => :paginatable
  end

  namespace :admin do
    resources :users, concerns: :paginatable
  end

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  # post 'signup', to: 'users#create', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # post 'login', to: 'sessions#create', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'movies#index'

end

app/controllers/reviews_controller.rb
 class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :set_review

  def index
    @reviews = movie.reviews.all
  end

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  private

  def movie
    @movie ||= Movie.find(params[:movie_id])
  end

  def set_review
    @review ||= movie.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.text_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<blockquote>
  <p><%= review.text %></p>
  <div class="row">
    <div class="col-xs-6">
      <p class="text-muted"><%= review.rating_out_of_ten %>/10</p>
    </div>
    <div class="col-xs-6 text-right">
      <small class="text-muted pull-right"><%= review.user.full_name %></small>
    </div>
  </div>
</blockquote>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<%= render @reviews %>

<%= link_to "Return to #{movie.title}", movie, class: "btn btn-primary" %>
<%= link_to 'New Review', [:new, movie, :review], class: "btn btn-default" %>

app/views/reviews/new.html.erb
 <%= link_to "Back to movie", movies_path %>

<h1>New Movie</h1>

<%= render 'form' %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Run time:</strong>
  <%= @movie.run_time %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>