config/routes.rb
Rails.application.routes.draw do

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :movies, concerns: :paginatable do
    resources :reviews, :concerns => :paginatable
  end

  namespace :admin do
    resources :users, concerns: :paginatable
  end

  resources :users, only: [:new, :create] do
    member do
      get :confirm_email
    end
  end

  resources :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  # resources :sessions, only: [:new, :create, :destroy]

  # get 'signup', to: 'users#new', as: 'signup'
  # post 'signup', to: 'users#create', as: 'signup'
  # get 'login', to: 'sessions#new', as: 'login'
  # post 'login', to: 'sessions#create', as: 'login'
  # get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'movies#index'

end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#b91d47">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
  <div class="container">
    <div class="navbar-text pull-left">
    <% if current_user %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
      <% if current_user.admin? %>
        <span class="label label-warning">Administrator</span>
      <% end %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" rel="home" href="/movies" title="Bad Apples">
        <img id="brandname" alt="Bad Apples" src="/assets/bad_apples_text.png">
      <img id="brandlogo" src="https://upload.wikimedia.org/wikipedia/commons/d/dc/Apple_with_worm_dan_gerh_01.svg"></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-brand-centered">
      <ul class="nav navbar-nav">
        <!--         <%= navlink("Movies",Movie) %>
        -->        <% if admin? %>
        <%= navlink("Users",[:admin, User]) %>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <%= form_tag movies_url, class: 'form-inline', method: :get do %>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
        <div class="form-group ">
          <label class="sr-only">Search</label>
          <%= text_field_tag( :search, nil, {class: 'form-control', placeholder: "Title/Director/Plot"}) %>
        </div>
        <%= submit_tag "Search", class: 'btn btn-primary' %>
        <% end %>
        <!-- <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">Submit</button> -->
        </form>
        <% if current_user %>
        <div class='navbar-text navbar-right' style="margin-right:10px;">
          <strong>Welcome <%= current_user.full_name %><strong>
        </div>
        <div class='navbar-form navbar-right'>
          <%= link_to "Log out", session_path("current"), method: :delete, class: "btn btn-success" %>
        </div>
        <% else %>
        <div class='navbar-form navbar-right'>
          <%= form_tag sessions_path do %>
          <div class="form-group">
            <%= label_tag 'email', nil, class: "sr-only" %>
            <%= text_field_tag 'email', nil, class: "form-control", placeholder: "email" %>
          </div>
          <div class="form-group">
            <%= label_tag 'password', nil, class: "sr-only" %>
            <%= password_field_tag 'password', nil, class: "form-control", placeholder: "password" %>
          </div>
          <div class="form-group">
            <%= submit_tag "Sign In", class: "btn btn-success" %>
          </div>
          <div class="form-group">
            <%= link_to "Sign Up", new_user_path, class: "navbar-signup" %>
          </div>
          <% end %>
        </div>
        <% end %>
        </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <%= render 'layouts/favicon' %>
    <title>Bad Apples</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
        </button>
        <%= content_tag(:div, value) %>
      </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </body>
</html>